python flickr2pelagios.py palestineexplorationfund 'The Palestine Exploration Fund'
python flickr2pelagios.py carolemage 'Following Hadrian'
python flickr2pelagios.py dandiffendale 'Dan Diffendale'
python flickr2pelagios.py dankate 'Daniel and Kate'
python flickr2pelagios.py APAAME 'Aerial Photographic Archive for Archaeology in the Middle East'
python flickr2pelagios.py 99690453@N02 'Sarah E. Bond'
python flickr2pelagios.py 65973181@N05 'Ethan Gruber'
python flickr2pelagios.py ryanfb 'Ryan Baumann'
